language: dart

dart:
# - dev currently the dartfmt failing on dev
 - stable

addons:
  chrome: stable

before_install:
  - chmod ugo+x tool/travis.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache

stages:
#  - presubmit
  - test

jobs:
  include:
#    - stage: presubmit
#      env: PKG="skawa_material_components"
#      script: ./tool/travis.sh presubmit
    - stage: test
      env: PKG="skawa_material_components"
      script: ./tool/travis.sh test

#    - stage: presubmit
#      env: PKG="skawa_components"
#      script: ./tool/travis.sh presubmit
    - stage: test
      env: PKG="skawa_components"
      script: ./tool/travis.sh test
