name: skawa_components
version: 0.0.1

dependencies:
  angular2: ^3.1.0
  angular_components: ^0.5.1

dev_dependencies:
  sass_builder: ^0.1.0

#dependency_overrides:
#  build: 0.9.0

transformers:
- angular2
