name: skawa_components
version: 1.0.0+4
authors:
  - Hars치nyi Tam치s (valakis) <tams.harsnyi@google.com>
  - Szepesh치zi Andr치s <szepeshazi@gmail.com>
description:
  Additional components for AngularDart based on Material Design principles. These reusable components are not part of the official  Material Components (https://material.io/design/components/) library.
homepage: https://github.com/skawa-universe/skawa_components

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.12.0
  markdown: ^2.0.2
  js: ^0.6.1+1
  intl: ^0.15.7
  sass_builder: ^2.1.2

dev_dependencies:
  test: ^1.5.1
  angular_test: ^2.1.0
  pageloader: 3.0.3
  html_unescape: ^1.0.1+2
  mockito: ^4.0.0
  build_config: ^0.3.1+4
  build_test: ^0.10.6
  build_runner: ^1.2.3
  build_web_compilers: ^1.1.0
dependency_overrides:
  package_resolver: 1.0.6