name: skawa_components
version: 1.0.0-beta

environment:
  sdk: '>=2.1.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  build_config: ^0.3.1+4
  markdown: ^2.0.2

dev_dependencies:
  test: ^1.3.0
  angular_test: ^2.1.0
#  pageloader: ^3.0.2
  html_unescape: ^1.0.1+2
  mockito: ^3.0.0
  build_test: ^0.10.3+3
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.4+2