name: skawa_components
version: 1.0.0

environment:
  sdk: '>=2.1.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.10.1
  build_config: ^0.3.1+4
  markdown: ^2.0.2

dev_dependencies:
  test: ^1.5.1
  angular_test: ^2.1.0
  pageloader: 3.0.2
  html_unescape: ^1.0.1+2
  mockito: ^3.0.0
  build_test: ^0.10.3+4
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
dependency_overrides:
  analyzer: 0.34.0
  build_resolvers: 0.2.2+7
