name: skawa_components
version: 1.0.0+1
authors:
  - Hars치nyi Tam치s (valakis) <tams.harsnyi@google.com>
  - Szepeh치zi Andr치s <szepeshazi@gmail.com>
description:
  Additional non Material Design components for AngularDart.
homepage: https://github.com/skawa-universe/skawa_components

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.10.1
  markdown: ^2.0.2

dev_dependencies:
  test: ^1.5.1
  angular_test: ^2.1.0
  # currently necessary for angular 5.2.0 with bumped analyzer version
  pageloader:
    git: https://github.com/skawa-universe/pageloader
  html_unescape: ^1.0.1+2
  mockito: ^3.0.0
  build_config: ^0.3.1+4
  build_test: ^0.10.3+4
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
