name: skawa_material_components
version: 1.0.0-beta

environment:
  sdk: '>=2.0.0-dev.46.0 <2.0.0'

dependencies:
  angular: 5.0.0-alpha+15
  angular_components: 0.9.0-alpha+15
  build_config: ^0.2.5

dev_dependencies:
  ansicolor: ^0.0.9
  test: ^1.0.0
  angular_test: ^2.0.0-alpha+13
  pageloader:
  html_unescape: ^0.1.5
  mockito: ^1.0.1
  grinder: ^0.8.1

